// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ReceiveMessage():Promise<string>;

export function SendMessage(arg1:string):Promise<void>;
